### ISSUE TITLE
애니메이션 추가한 것... 나중에 해야되는 것인가?

### ISSUE THREAD

**Issue by JungHanYoung** [JungHanYoung/MafiaGame_single_react#1]
게임 기능을 다 구현하고 넣어야 될 것 같기도함.. 근데 이전에 만들어진 것... 그니까 정확한 UI같은게 있어야 좀 더 성취감이 있을 것 같은데.. 없어서 의욕이 좀처럼 쉽지 않은 것 같..ㅠ

**Comment by ByeongUkChoi** [comment]
적당히 애니메이션을 넣으면서 하면 재미있을것 같ㅜㅅㅜ
일단 부트스트랩이나 그런 css를 입히는것도 좋을듯
